//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFQ.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RFQ.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve Altex configuration settings. Please check that settings under &apos;{0}&apos; group exists..
        /// </summary>
        internal static string AltexSettingsReadErrorMessage {
            get {
                return ResourceManager.GetString("AltexSettingsReadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve name of the component used for RFQ setup.  Insure that there all necessary settings provided for Altex setup.   .
        /// </summary>
        internal static string ComponentNameReadErrorMessage {
            get {
                return ResourceManager.GetString("ComponentNameReadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - highlights service debugging text..
        /// </summary>
        internal static string DebugColorMessage {
            get {
                return ResourceManager.GetString("DebugColorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - highlights service error text..
        /// </summary>
        internal static string ErrorColorMessage {
            get {
                return ResourceManager.GetString("ErrorColorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - highlights service critical error..
        /// </summary>
        internal static string FatalErrorColorMessage {
            get {
                return ResourceManager.GetString("FatalErrorColorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve configuration for EVSP tracking interval. Please check that setting exist and provided as valid number..
        /// </summary>
        internal static string GTNTrackingIntervalReadErrorMessage {
            get {
                return ResourceManager.GetString("GTNTrackingIntervalReadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve heartbeat topic value.  Insure that there all necessary settings provided for Altex setup..
        /// </summary>
        internal static string HeartbeatTopicReadErrorMessage {
            get {
                return ResourceManager.GetString("HeartbeatTopicReadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - highlights service informational text..
        /// </summary>
        internal static string InfoColorMessage {
            get {
                return ResourceManager.GetString("InfoColorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option {0} is not supported..
        /// </summary>
        internal static string OptionNotSupportedErrorMessage {
            get {
                return ResourceManager.GetString("OptionNotSupportedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit....
        /// </summary>
        internal static string PressKeyToExitMessage {
            get {
                return ResourceManager.GetString("PressKeyToExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to stop service....
        /// </summary>
        internal static string PressKeyToStopMessage {
            get {
                return ResourceManager.GetString("PressKeyToStopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve configuration for RFQ heartbeats interval. Please check that setting exist and provided as valid number..
        /// </summary>
        internal static string RFQHeartbeatIntervalReadErrorMessage {
            get {
                return ResourceManager.GetString("RFQHeartbeatIntervalReadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve &apos;StartAs&apos; option from the configuration file. In order to start application as console the &apos;Console&apos; option should be provided, otherwise &apos;Service&apos;. .
        /// </summary>
        internal static string StartAsReadErrorMessage {
            get {
                return ResourceManager.GetString("StartAsReadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color settings:.
        /// </summary>
        internal static string TextColorMessage {
            get {
                return ResourceManager.GetString("TextColorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - highlights successful execution text..
        /// </summary>
        internal static string TraceColorMessage {
            get {
                return ResourceManager.GetString("TraceColorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occurred..
        /// </summary>
        internal static string UnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("UnhandledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - highlights service warn text..
        /// </summary>
        internal static string WarnColorMessage {
            get {
                return ResourceManager.GetString("WarnColorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to RFQ service!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
